import { React } from "react"
import { Box, Heading, Text } from "@chakra-ui/react"
import { PiTriangleFill } from "react-icons/pi"


function Projects() {
    return (
        <Box display={"flex"} fontFamily={"mono"} flexDir={"column"} mt={"2em"} color={"white"}>
            <Heading fontSize={"lg"} pb={"0.5"}>Projects 📁</Heading>
            <Box display={"flex"} flexDir={"row"} mt={"1.5em"}>
                <Box display={"flex"} flexDir={"row"} pr={"1.5em"} width={"35%"}>
                    <Text>2023</Text>
                </Box>
                <Box display={"flex"} flexDir={"column"} width={"65%"}>
                    <Text>Post-Tonal Theory Library ⬅️</Text>
                    <Text color={"gray.300"} mt={"0.5em"}>A JavaScript library built to assist analysis of post-tonal music. Comes with a Pitch Class Set class that contains different methods for altering the PCS according to conventional procedures.</Text>
                    <Box display={"flex"} flexDir={"row"} mt={"0.5em"}>
                    <Text color={"gray.400"}>JavaScript</Text>
                    </Box>
                   
                </Box>

            </Box>
            <Box display={"flex"} flexDir={"row"} mt={"1.5em"}>
                <Box display={"flex"} flexDir={"row"} pr={"1.5em"} width={"35%"}>
                    <Text>January 2022</Text>
                </Box>
                <Box display={"flex"} flexDir={"column"} width={"65%"}>
                    <Text >ELI5-AI ⬅️</Text>
                    <Text color={"gray.300"} mt={"0.5em"}>An online newsletter about developments in AI and Machine Learning with a meta twist: all the content is generated by AI. </Text>
                    <Box display={"flex"} flexDir={"row"} mt={"0.5em"}>
                    <Text color={"gray.400"}>React • Express • PostgreSQL</Text>
                    </Box>
                   
                </Box>

            </Box>

        </Box>
    )
}

export default Projects